# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-13 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty_od',
            old_name='odpurpose',
            new_name='od_purpose',
        ),
    ]
