# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-15 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='nptelfaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('empname', models.CharField(max_length=50)),
                ('coursename', models.CharField(max_length=100)),
                ('percent', models.FloatField()),
            ],
        ),
    ]
