# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-15 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_nptelfaculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nptelfaculty',
            name='percent',
            field=models.IntegerField(),
        ),
    ]
