# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-12 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_foo'),
    ]

    operations = [
        migrations.CreateModel(
            name='up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='foo',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'Female')], max_length=1),
        ),
    ]
